langauge: cpp
dist: trusty
sudo: required
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
install:
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
script: 
  - ./install.sh --build=Debug
